### ISSUE TITLE
Bridges Food Bar menu issue

### ISSUE THREAD

**Issue by vinczu** [ijanos/ebedke#11]
Hi,

Currently there is no menu on Bridges page, but it is there on Bridges facebook's page?
Would you please check if it would be possible to check first the webpage (http://bridges.hu/#heti-menu) and if nothing is found there, try to get the menu from their FB page (https://www.facebook.com/BridgesFoodBar/)?

Thanks,
vinczu

**Comment by ijanos** [comment]
Tudok róla. A facebook oldalon csak egy kép van, ami hétről hétre más dimenziójú, azt feldolgozni nyűgös, egyszerűbb lenne a facebookon kommentelni nekik, hogy szeretnénk ha frissítenék a honlapot :) persze a héten már felesleges, jövőhéten meglátjuk hogy egyszeri dolog volt-e. Ezt a issuet most lezárom, egyelőre WONTFIX.

**Comment by vinczu** [comment]
Ok, intézem

**Comment by ijanos** [comment]
már fenn is van a jövőheti menü, szerintem a héten csak megfeledkeztek róla

**Comment by vinczu** [comment]
viszont az erdekes, hogy mara mutatja a jovohet penteki menut

**Comment by ijanos** [comment]
Persze, hisz a menü nem öregebb mint egy hét és péntek volt. Aki pénteken este ebédmenüket néz az így járt.

**Comment by vinczu** [comment]
ok, de mi van ha ezt pentek reggel teszik ki?

**Comment by ijanos** [comment]
Annak nem lenne sok értelme mert akkor hol lehetne megnézni az aznapi menüt? :)

**Comment by vinczu** [comment]
Arra gondolok, hogy egy hetig nem raknak ki menut(mint most), aztan pentek reggel kirakjak a jovohetit. Rosszat fog mutatni a page/app
