### ISSUE TITLE
Sushiroll

### ISSUE THREAD

**Issue by vinczu** [ijanos/ebedke#12]
Hi Janos,

Would you please add Sushiroll? https://www.facebook.com/sushirollcorvin/
Quality food, recommended, if you like sushi.

Thanks,
vinczu

**Comment by ijanos** [comment]
Their facebook page is not public (try to open it in an incognito browser). I cannot read the posts until they change this.

**Comment by vinczu** [comment]
Ok, talked with them, wrote on facebook, no answer -> let's close this issue
