### ISSUE TITLE
Kajahu

### ISSUE THREAD

**Issue by PZoltan** [ijanos/ebedke#21]
Hi,

Kajahu has opened a place near Corvin. Could you add the Corvin filter as well to that place?
(I tried but I had no permission to contribute)

Thanks

**Comment by Zolikon** [comment]
I think I have found out how to do this. This is my first time contributing to an external repo. :)

**Comment by ijanos** [comment]
The README is outdated a bit now, I am going to document this at some point, glad you figured it out by yourself 👍
